blog/Blog-master/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'auth/google_oauth2', as: :sign_in_with_google
  get 'auth/google_oauth2/callback' => 'callbacks#google'
  get 'auth/facebook', as: :sign_in_with_facebook
  get 'auth/facebook/callback' => 'callbacks#facebook'

    root 'home#index'
    get '/about' => 'home#about', as: :about
    resources :posts do
      resources :comments
      resources :favourites, only: [:create, :destroy]
      resources :stars, only: [:create, :update, :destroy]
    end
    resources :users do
      get :edit, on: :collection
      patch :update, on: :collection
    end
    resources :sessions, only: [:new, :create] do
      delete :destroy, on: :collection
    end
    resources :password_resets
    resources :tags, only: [:index, :show]
end

blog/Blog-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <navbar class="navbar">
      <%= link_to 'Home', root_path %>
      <%= link_to 'About', about_path %>
      <%= link_to 'All Posts', posts_path %>

    <div class='pull-right'>
      <% if session[:user_id].present? %>
        <p>Hello <%= current_user.first_name %></p>
         <%= link_to 'Update User Info', edit_users_path%>
         <%= link_to 'Sign Out', sessions_path, method: :delete %>
         <%= link_to 'Favourites', users_path %>
         <%= link_to 'New Post', new_post_path %>
      <% else %>
         <%= link_to 'Sign Up', new_user_path %>
         <%= link_to 'Sign In', new_session_path %>
         <%= link_to "Sign in with Google", sign_in_with_google_path, id: "sign_in" %>
         <%= link_to "Sign in with Facebook", sign_in_with_facebook_path, id: "sign_in" %>
       <% end %>
     </div>

   </navbar>
    <div class='main'>
      <%= alert || notice %>
      <%= yield %>
    </div>

  </body>
</html>