blog/Blog-master/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'auth/google_oauth2', as: :sign_in_with_google
  get 'auth/google_oauth2/callback' => 'callbacks#google'
  get 'auth/facebook', as: :sign_in_with_facebook
  get 'auth/facebook/callback' => 'callbacks#facebook'

    root 'home#index'
    get '/about' => 'home#about', as: :about
    resources :posts do
      resources :comments
      resources :favourites, only: [:create, :destroy]
      resources :stars, only: [:create, :update, :destroy]
    end
    resources :users do
      get :edit, on: :collection
      patch :update, on: :collection
    end
    resources :sessions, only: [:new, :create] do
      delete :destroy, on: :collection
    end
    resources :password_resets
    resources :tags, only: [:index, :show]
end

blog/Blog-master/app/models/tag.rb
class Tag < ApplicationRecord

  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  
end

blog/Blog-master/app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @tags = Tag.find params[:id]
  end

end

blog/Blog-master/app/views/tags/index.html.erb
<h1>All Tags</h1>

<% @tags.each do |t| %>
  <%= link_to t.name, tag_path(t) %> (<%= t.posts.size %> Posts) <br />
<% end %>

blog/Blog-master/app/views/tags/show.html.erb
<h1>Posts by Tag: <%=@tags.name%></h1>

<% @tags.posts.each do |t| %>
  <%= link_to t.title, post_path(t) %><br />
<% end %>