blog/Blog-master/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'auth/google_oauth2', as: :sign_in_with_google
  get 'auth/google_oauth2/callback' => 'callbacks#google'
  get 'auth/facebook', as: :sign_in_with_facebook
  get 'auth/facebook/callback' => 'callbacks#facebook'

    root 'home#index'
    get '/about' => 'home#about', as: :about
    resources :posts do
      resources :comments
      resources :favourites, only: [:create, :destroy]
      resources :stars, only: [:create, :update, :destroy]
    end
    resources :users do
      get :edit, on: :collection
      patch :update, on: :collection
    end
    resources :sessions, only: [:new, :create] do
      delete :destroy, on: :collection
    end
    resources :password_resets
    resources :tags, only: [:index, :show]
end

blog/Blog-master/app/models/user.rb
class User < ApplicationRecord
  
  attr_accessor :current_password
  has_many :comments, dependent: :nullify
  has_many :posts, dependent: :nullify
  has_many :favourites, dependent: :destroy
  has_many :favourite_posts, through: :favourites, source: :post
  has_many :stars, dependent: :destroy
  has_many :starred_posts, through: :stars, source: :post

  has_secure_password

  before_validation :downcase_email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
                    uniqueness: {case_sensitive: false },
                    format: VALID_EMAIL_REGEX,
                    unless: :from_oauth?

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      full_name = (auth.info.name).split
      user.first_name = full_name[0]
      user.last_name = full_name[1]
      user.email = auth.info.email
      user.password = SecureRandom.hex(32)
      user.provider = auth.provider
      user.uid = auth.uid
      user.oauth_token = auth.credentials.token
      user.oauth_secret = auth.credentials.secret
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.oauth_raw_data = auth
      user.save!
    end
  end

  def full_name
   "#{first_name} #{last_name}".strip.squeeze(' ').titleize
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
  end

  def from_oauth?
    provider.present? && uid.present?
  end

  def signed_in_with_facebook?
    uid.present? && provider == 'facebook'
  end

  private

  def downcase_email
    self.email.downcase! if email.present?
  end

end

blog/Blog-master/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new find_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Thanks for signing up.'
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
   @user = current_user
   if @user && @user.authenticate(user_params[:current_password])
     if @user.update find_params
       redirect_to home_path, notice: "Successfully updated"
     else
       render :edit
     end
   else
     flash.now[:alert] = "Wrong credentials. Please try again."
     render :edit
   end
 end

  def destroy
    @user = current_user
    session[:user_id] = nil
    @user.destroy
    redirect_to root_path, notice: 'User deleted'
  end

  def index
  end

  private

  def find_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end

end

blog/Blog-master/app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= @user.errors.full_messages.join(', ') %>
<%= form_for @user do |f| %>

  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :current_password %>
    <%= f.password_field :current_password %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit %><br />
  <button><%= link_to 'Delete User', user_path(@user),
  method: :delete,
  data: {confirm: 'are you sure?'} %></button>
  
<%end%>

blog/Blog-master/app/views/users/index.html.erb
<h1>All Favourite Posts</h1>

<% current_user.favourites.each do |f| %>
  <%=link_to f.post.title, post_path(f.post) %> <hr />
<% end %>

blog/Blog-master/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= @user.errors.full_messages.join(', ') %>
<%= form_for @user do |f| %>

  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit %>

<%end%>